spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  security:
    jwt:
      secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentOnlyChangeInProduction}
      access-token-expiration: 900000 # 15 min
      refresh-token-expiration: 2592000000 # 30 jours

logging:
  level:
    org.springframework.security: DEBUG