spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  security:
    jwt:
      secret: ${JWT_SECRET:mySuperSecretKeyForDevelopmentChangeInProduction123!}
      access-token-expiration: 900000  # 15 minutes
      refresh-token-expiration: 2592000000  # 30 jours

server:
  port: 8080

logging:
  level:
    com.youssef.spring.security: DEBUG  # ✅ VOTRE PACKAGE CORRECT
    org.springframework.security: DEBUG  # Pour voir les logs de sécurité
    org.hibernate.SQL: DEBUG  # Pour voir les requêtes SQL.youssef.spring.security: DEBUG